---
name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - package: gcc
            bin: g++
          - package: clang
            bin: clang++
    steps:
      - name: checkout-scm
        uses: actions/checkout@v2
      - name: setup
        run: sudo apt install ${{ matrix.compiler.package }} make
      - name: test
        run: make test CXX=${{ matrix.compiler.bin }}
